## this workflow uses the github action here: https://github.com/marketplace/actions/slack-pr-open-notification

name: Send Slack Notifications

on: 
  pull_request:
    types: [labeled]  
    
jobs:
  slackNotification:
    if: contains(github.event.pull_request.labels.*.name, 'ready for review')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env: 
        SLACK_WEBHOOK_URL : ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_USERNAME: dbt-reviewer
        SLACK_ICON: ':sparkles:'
        SLACK_LINK_NAMES: true       

    
    

        


