name: Send Slack Notifications

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'ready for review')
    runs-on: ubuntu-latest

    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "pr_name": "${{ github.event.pull_request.title }}",
              "pr_link": "${{ github.event.pull_request.html_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.T052AUSAQM7/B05FLLTRYES/xhNawNSNZrpgnN7zvdLKlS5V }}
