name: Send Slack Notifications

on: 
  pull_request:
    types: [labeled]  
    
jobs:
  slackNotification:
    if: contains(github.event.pull_request.labels.*.name, 'ready for review')
    runs-on: ubuntu-latest
    
    steps:
    - name: actions
      uses: actions/checkout@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_CHANNEL: general
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_TITLE: Post Title
        PULL_REQUEST_NUMBER : ${{ github.event.pull_request.number }}
        PULL_REQUEST_URL : ${{ github.event.pull_request.html_url }}
        PULL_REQUEST_BODY : ${{ github.event.pull_request.body }}
        MAKE_PRETTY: false
        
